spring:
  profiles:
    active: local
    include:
      - key
  jpa:
    show-sql: true
    properties:
      hibernate:
        id:
          new_generator_mappings: false

  #      ddl-auto: update #배포시 validate
  datasource:
    url: jdbc:mariadb://localhost:3306/test
    hikari:
      username: root
      password: bitc5600
      driver-class-name: org.mariadb.jdbc.Driver
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: false
  thymeleaf:
    cache: false




