spring:
  profiles:
    active: local
    include:
      - key
  jpa:
    show-sql: true
    properties:
      hibernate:
        id:
          new_generator_mappings: false
  datasource:
    url: jdbc:mariadb://localhost:3306/test
    hikari:
      username: root
      password: bitc5600
      driver-class-name: org.mariadb.jdbc.Driver
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: false
  thymeleaf:
    cache: false
    prefix: classpath:/static/templates/
  web:
    cors:
      allow-credentials: true
      allowed-origins:
        - "http://example.com"
        - "https://anotherdomain.com"
      allowed-methods:
        - "GET"
        - "POST"
        - "PUT"
        - "DELETE"
      allowed-headers:
        - "Authorization"
        - "Content-Type"
      exposed-headers:
        - "Custom-Header"
      max-age: 3600
  server:
    port: 8080

